### ISSUE TITLE
Missing build id environment variable for github actions

### ISSUE THREAD

**Issue by anark** [KnapsackPro/knapsack-pro-cypress#45]
In the record section setting of the readme(https://github.com/KnapsackPro/knapsack-pro-cypress#how-to-record-ci-builds-in-cypress-dashboard) the environment variable to use for the BUILD_ID from github actions is missing.

Does anyone know what the ENV variable on github actions is and if it can be added there?

**Comment by ArturT** [comment]
Hi @anark 

You can use `GITHUB_RUN_ID`. A unique number for each run within a repository. This number does not change if you re-run the workflow run.

https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

I will update FAQ in the readme and on our FAQ page https://knapsackpro.com/faq/question/how-to-record-ci-builds-in-cypress-dashboard

BTW If you need any help please send an email to support https://knapsackpro.com/contact and I can review your recorded CI builds to make sure all works fine for you :)

**Comment by ArturT** [comment]
Related improvement for Cypress https://github.com/KnapsackPro/knapsack-pro-cypress/pull/47
