### ISSUE TITLE
Bitbucket Guideline - Issues to know exactly how I have to install this by using bitbucket

### ISSUE THREAD

**Issue by hvaandres** [KnapsackPro/knapsack-pro-cypress#56]
I'm pretty new to this software and I'm looking to move forward with your tool to install it on my current cypress project and my bitbucket pipeline, but I'm not sure how I have to configure my YAML file. Do you have any guides for bitbucket or any examples of how the YAML file should look?

**Comment by ArturT** [comment]
@knapsack-pro/cypress uses Knapsack Pro Queue Mode to distribute tests in parallel.
Please see this article to see how Queue Mode works:
https://docs.knapsackpro.com/2020/how-to-speed-up-ruby-and-javascript-tests-with-ci-parallelisation

I'm not familiar with Bitbucket but I know some of our users use BitBucket Pipeline to run parallel jobs. You may want to check BitBucket docs to see how to configure parallel jobs for a CI build.

Then each parallel job should run Knapsack Pro command with a different value for KNAPSACK_PRO_CI_NODE_INDEX
https://github.com/KnapsackPro/knapsack-pro-cypress#other-ci-provider

```
# Step for first CI node - your first docker container should run this command
KNAPSACK_PRO_CI_NODE_TOTAL=2 KNAPSACK_PRO_CI_NODE_INDEX=0 $(npm bin)/knapsack-pro-cypress

# Step for second CI node - your second docker container should run this command
KNAPSACK_PRO_CI_NODE_TOTAL=2 KNAPSACK_PRO_CI_NODE_INDEX=1 $(npm bin)/knapsack-pro-cypress
```

This way you would split tests between 2 docker containers. 

Please follow each step here to properly set up required environment variables in your CI
https://github.com/KnapsackPro/knapsack-pro-cypress#configuration-steps

I guess you can find info for BitBucket Pipeline and how to run parallel jobs here:
https://support.atlassian.com/bitbucket-cloud/docs/set-up-or-run-parallel-steps/
https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/


Here you can see examples for Jenkins and Cypress
https://docs.knapsackpro.com/2019/cypress-parallel-testing-with-jenkins-pipeline-stages

Here is another article from one of our users who uses Cypress and Gitlab CI
https://docs.knapsackpro.com/2021/faster-pipelines-with-knapsack-pro-by-parallelizing-cypress-tests-on-gitlab-ci

This should get you the idea.

Cheers
