### ISSUE TITLE
Can't force disable Cypress recording

### ISSUE THREAD

**Issue by amvd** [KnapsackPro/knapsack-pro-cypress#66]
I previously had my test runner set up to record my tests and send them to Cypress.io, and now I'm attempting to use this library instead. I have it up and running and it seems great so far, except I get this message in between each test.

```
This project has been configured to record runs on our Dashboard.

It currently has the projectId: xxxxx

You also provided your Record Key, but you did not pass the --record flag.

This run will not be recorded.

If you meant to have this run recorded please additionally pass this flag.

  cypress run --record

If you don't want to record these runs, you can silence this warning:

  cypress run --record false

https://on.cypress.io/recording-project-runs
```

Following its advice, I instead ran `knapsack-pro-cypress run --record false`, but now Cypress refuses to run at all, saying:

```
You passed the --ci-build-id, --group, --tag, or --parallel flag without also passing the --record flag.

The --group flag you passed was: fff90030-b205-42da-aadb-d9f53b8120b0

These flags can only be used when recording to the Cypress Dashboard service.

https://on.cypress.io/record-params-without-recording
```

This seems to be caused by [this line](https://github.com/KnapsackPro/knapsack-pro-cypress/blob/master/src/cypress-cli.ts#L30) added in #47 which adds a group ID whenever the --record flag is passed.

Granted, I believe it's only doing this because there is a `CYPRESS_RECORD_KEY` set in my environment, and that removing that would also solve the issue for me personally. However, I can imagine users potentially wanting to be able to disable test recording sometimes without having to change their environment variables.

I propose changing this to only add the group ID if the --record argument isn't `false`.

**Comment by ArturT** [comment]
Hi @amvd 

> However, I can imagine users potentially wanting to be able to disable test recording sometimes without having to change their environment variables.

Good point.

I've released `@knapsack-pro/cypress` version 4.4.1 with the proposed improvement.

FYI If you would like to use `@knapsack-pro/cypress` and at the same time record tests in Cypress Dashboard you can do it as described here https://knapsackpro.com/faq/question/how-to-record-ci-builds-in-cypress-dashboard
