### ISSUE TITLE
[Security] Upgrade axios dependency in `@knapsack-pro/core` to  0.21.2 or later

### ISSUE THREAD

**Issue by gustaff-weldon** [KnapsackPro/knapsack-pro-cypress#70]
There's a known security vulnerability in axios. Upgrade axios to version 0.21.2 or later.

https://github.com/advisories/GHSA-cph5-m8f7-6c5x

```
> yarn why axios -R
   └─ @knapsack-pro/cypress@npm:4.5.0 [dc3fc] (via npm:^4.5.0 [dc3fc])
      └─ @knapsack-pro/core@npm:3.1.1 (via npm:^3.1.1)
         └─ axios@npm:0.21.1 (via npm:0.21.1)
```

<img width="1108" alt="Screenshot 2022-02-07 at 11 34 20" src="https://user-images.githubusercontent.com/411756/152771704-efe14ff3-7c38-48aa-a2d1-f83523b92990.png">

**Comment by ArturT** [comment]
@gustaff-weldon There is a new version 4.6.0 of `@knapsack-pro/cypress` package. Please update it in your project.

**Comment by gustaff-weldon** [comment]
@ArturT perfect, thank you!

**Comment by ArturT** [comment]
@gustaff-weldon There is also a newer version `@knapsack-pro/cypress` 5.0.0 that supports Cypress 10.x
There are breaking changes there:
https://github.com/KnapsackPro/knapsack-pro-cypress/blob/master/CHANGELOG.md#v500-2022-06-13
More info: https://github.com/KnapsackPro/knapsack-pro-cypress/pull/77
