### ISSUE TITLE
Feature: Support exclusion pattern with KNAPSACK_PRO_TEST_FILE_EXCLUDE_PATTERN env var

### ISSUE THREAD

**Issue by renehernandez** [KnapsackPro/knapsack-pro-cypress#84]
As the title say, leverage `KNAPSACK_PRO_TEST_FILE_EXCLUDE_PATTERN` in  `knapsack-pro-cypress`

**Comment by ArturT** [comment]
It could work similarly to what we have for Jest.
https://github.com/KnapsackPro/knapsack-pro-jest/pull/10

We could use `KNAPSACK_PRO_TEST_FILE_EXCLUDE_PATTERN` name to keep it consistent across all Knapsack Pro clients.

Would you like to help prepare a PR?

**Comment by renehernandez** [comment]
I'll get a PR tomorrow

**Comment by ArturT** [comment]
Thank you. `@knapsack-pro/cypress` 5.2.0 has been released.
