### ISSUE TITLE
Update for Cypress 12

### ISSUE THREAD

**Issue by wagnerpereira** [KnapsackPro/knapsack-pro-cypress#89]
It's possible to update cypress dependency to cypress current version? 12

**Comment by ArturT** [comment]
Yes. I'll look into removing max Cypress version limit on the peer dependency.

Can you for now try to install `@knapsack-pro/cypress` with `npm install--legacy-peer-deps`. Most likely it should work fine with Cypress 12.

**Comment by wagnerpereira** [comment]
I'm using yarn as JS dependecy manager.

> Yes. I'll look into removing max Cypress version limit on the peer dependency.
> 
> Can you for now try to install `@knapsack-pro/cypress` with `npm install--legacy-peer-deps`. Most likely it should work fine with Cypress 12.

**Comment by ArturT** [comment]
Maybe you could try `yarn install --force`. https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-force

I don't see the `--legacy-peer-deps` option available for yarn https://yarnpkg.com/cli/install but `--force` was not described there to.
Maybe `yarn install --legacy-peer-deps` would work just fine. Or  `yarn install --force` should do the trick.

---

npm flags force vs legacy-peer-deps: https://stackoverflow.com/questions/66020820/npm-when-to-use-force-and-legacy-peer-deps

**Comment by ArturT** [comment]
BTW Can you share the error that you see?

**Comment by wagnerpereira** [comment]
In fact I have no error @ArturT just the deprecation warning message:

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @knapsack-pro/cypress@5.3.1" has incorrect peer dependency "cypress@>=10.0.0 <11.0.0".
[4/4] Building fresh packages...
Done in [15](https://github.com/unimedrj/acordosweb/actions/runs/4067472353/jobs/7004862930#step:7:16).22s.
```

**Comment by ArturT** [comment]
Ok. That's good. It should not stop you from using Knapsack Pro.

I'll let you know when we get rid of the warning problem.

**Comment by mfittko** [comment]
+1

**Comment by ArturT** [comment]
A new version of the package @knapsack-pro/cypress (5.4.0) was published.
